// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountSys: typeof import('./src/components/AccountSys.vue')['default']
    Demo1: typeof import('./src/components/Demo1.vue')['default']
    MyAccountList: typeof import('./src/components/MyAccountList.vue')['default']
    MyToken01: typeof import('./src/components/MyToken01.vue')['default']
    MyWalletApp: typeof import('./src/components/MyWalletApp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDivider: typeof import('vant/es')['Divider']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanSpace: typeof import('vant/es')['Space']
    Web3Api: typeof import('./src/components/Web3Api.vue')['default']
  }
}
